-- Update job descriptions (run against existing snowisland DB)
SET NAMES utf8mb4;
DELETE FROM `job` WHERE `id` = 5;
UPDATE `job` SET `description` = '在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 1;
UPDATE `job` SET `description` = '格斗：在密谋、暴力冲突中，如果装备近距离武器增加威胁值。急救：花费 5 医疗资源，将“枪伤”改为“受伤”标记。' WHERE `id` = 2;
UPDATE `job` SET `description` = '在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 3;
UPDATE `job` SET `description` = '无职业技能。' WHERE `id` = 4;
UPDATE `job` SET `description` = '格斗：在密谋、暴力冲突中，如果装备近距离武器增加威胁值；调查玩家时夜晚骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 6;
UPDATE `job` SET `description` = '格斗：在密谋、暴力冲突中，如果装备近距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。巡逻：夜间行动，选择一个地点，当晚该地点内非统治者阵营玩家夜晚行动成功率 -30%，巡夜人知晓其行动类型；需要当天未处于“劳工/过劳”。' WHERE `id` = 7;
UPDATE `job` SET `description` = '使用牲畜设施获得食物 15 单位；或使用自留田设施获得 30 斤面粉。' WHERE `id` = 8;
UPDATE `job` SET `description` = '使用斧头获得 10 吨原木；使用电锯获得 30 吨原木。' WHERE `id` = 9;
UPDATE `job` SET `description` = '使用电钻获得 20 吨石料，否则 5 吨；该技能可额外增加避难所建造进度。' WHERE `id` = 10;
UPDATE `job` SET `description` = '职业与技能在不满 48 人时不开放；具体效果未在资料中详细说明。' WHERE `id` = 11;
UPDATE `job` SET `description` = '使用工具制备单制作材料/物品/武器；制作列表包括皮带弹袋、复合盾、鱼叉矛、规制箭矢和弓弩等。' WHERE `id` = 12;
UPDATE `job` SET `description` = '使用木板蒸汽箱将原木转化为木板；或使用切石机将石料转化为石墙。' WHERE `id` = 13;
UPDATE `job` SET `description` = '捕鱼：码头使用渔船设施，获得食物 10 单位或 20kg 鱼肉。格斗：在密谋、暴力冲突中，如果装备近距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 14;
UPDATE `job` SET `description` = '航海：码头使用货船设施获得 10kg 鱼肉；亦为远洋航行必要技能，对冒险者阵营有特殊用途。格斗：在密谋、暴力冲突中，如果装备近距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 15;
UPDATE `job` SET `description` = '远洋导航：为方舟终局提供更好的结局倾向，并查看所有天灾牌。射击：在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 16;
UPDATE `job` SET `description` = '搬运：搬运量永远是其他职业的两倍。斗殴：具体效果未详细说明（推测为格斗变体）。' WHERE `id` = 17;
UPDATE `job` SET `description` = '潜水：每天一次，码头使用，由主持人投 d6：1-5 获得食物 8 单位，6 获得沉船遗物。捕鱼：在码头使用渔船设施，获得食物 10 单位或 20kg 鱼肉。' WHERE `id` = 18;
UPDATE `job` SET `description` = '布道：每天一次，选择最多 3 人，使其下一个行动生产 +50%；或为最多 3 人消除诅咒。医疗：每天一次，选择一位或至多 5 位“受伤”玩家，花费 3 医疗资源每人消除“受伤”；选择一位或多位“过劳”玩家，花费 2 医疗资源每人消除“过劳”。' WHERE `id` = 19;
UPDATE `job` SET `description` = '医疗：每天一次，选择一位或至多 5 位“受伤”玩家，花费 3 医疗资源每人消除“受伤”；选择一位或多位“过劳”玩家，花费 2 医疗资源每人消除“过劳”。急救：花费 5 医疗资源，将“枪伤”改为“受伤”标记。' WHERE `id` = 20;
UPDATE `job` SET `description` = '特殊性：初始拥有大量资源和商店功能；无职业技能。' WHERE `id` = 21;
UPDATE `job` SET `description` = '烘焙：需要 5 单位食物与 15kg 木材制作 1 份便当；便当当天额外获得 1 个白天行动点，每人每天限 1 次。' WHERE `id` = 22;
UPDATE `job` SET `description` = '特殊性：初始拥有大量酒类与医用酒精；无职业技能。' WHERE `id` = 23;
UPDATE `job` SET `description` = '射击：在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 24;
UPDATE `job` SET `description` = '烘焙：需要 5 单位食物与 15kg 木材制作 1 份便当；便当当天额外获得 1 个白天行动点，每人每天限 1 次。' WHERE `id` = 25;
UPDATE `job` SET `description` = '急救：花费 5 医疗资源，将“枪伤”改为“受伤”标记。潜行：为谋略增加成功率，且无法被调查。' WHERE `id` = 26;
UPDATE `job` SET `description` = '射击：在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。潜行：为谋略增加成功率，且无法被调查。' WHERE `id` = 27;
UPDATE `job` SET `description` = '潜行：为谋略增加成功率，且无法被调查。' WHERE `id` = 28;
UPDATE `job` SET `description` = '每天一次，与一位死亡玩家建立私信交流，由主持人保底提供信息。' WHERE `id` = 29;
UPDATE `job` SET `description` = '你通过科学手段发现异常暴雪来临；可查看所有天灾牌，并为终局结算提供更好的结局倾向。' WHERE `id` = 30;
UPDATE `job` SET `description` = '为终局结算提供更好的结局倾向；可抽取一张天灾牌撕毁使其不生效，或让一张事件牌撕毁不生效。' WHERE `id` = 31;
UPDATE `job` SET `description` = '每天一次，修复一个被破坏的设施，花费 5 维修资源。' WHERE `id` = 32;
UPDATE `job` SET `description` = '每天一次，消耗一盒粉笔与 2 支铅笔，选择除自己外最多 2 名玩家，使其临时学会一项基础技能持续到次日白天结束；若已拥有则增产 50%。' WHERE `id` = 33;
UPDATE `job` SET `description` = '在密谋、暴力冲突中，如果装备远距离武器增加威胁值。如果调查玩家，可以选择在夜晚阶段骰 d6 寻找攻击机会，成功可发起小规模冲突；多人调查可袭击。' WHERE `id` = 34;
UPDATE `job` SET `description` = '为一位或多位玩家建立协议契约，可以指定违反协议的惩罚内容。' WHERE `id` = 35;
